# Generated by Django 5.2 on 2025-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('winery', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('number_of_ratings', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('inventory', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
