# Generated by Django 5.2 on 2025-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_created_at_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='winery',
            field=models.CharField(max_length=100),
        ),
    ]
